# Application
server:
  port: 5000

# Database
spring:
  datasource:
    url: 'jdbc:postgresql://db-dreamsbo.clptcbmsch2x.us-east-1.rds.amazonaws.com:5432/dreamsbo?currentSchema=pos'
    username: 'postgres'
    password: '0ZxCls7qI6vxiaIkgz9pycdXgA2ZpOiq2nvJhA'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

# Security
security:
  authentication:
    jwt:
      secret: 'c29tZXJhbmRvbWtleXdoaWNoaXNsb25nZW5vdWdodG9hbGlnbndpdGh0aGVqd3RzcGVjaWZpY2F0aW9u'
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000

# Cloud AWS
cloud:
  aws:
    enabled: false
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:}
      secret-key: ${AWS_SECRET_ACCESS_KEY:}
    region:
      static: ''
    stack:
      auto: false
    file:
      expiration-in-seconds: 604800

application:
  bucket:
    name: 'pos-storage'

logging:
  level:
    org:
      springframework:
        web: debug
